<?php
require get_theme_file_path('/inc/functions.php');
require get_theme_file_path('/inc/helpers.php');
require get_theme_file_path('/import-assets/reset-css-js.php');
require get_theme_file_path('/import-assets/import-css-js.php');
require get_theme_file_path('/inc/ajax.php');
require get_theme_file_path('/inc/api.php');
require get_theme_file_path('/inc/shortcodes.php');
add_action( 'acf/include_fields', function() {
if ( ! function_exists( 'acf_add_local_field_group' ) ) {
return;
}

acf_add_local_field_group( array(
'key' => 'group_6a12e4fa5ee15',
'title' => 'Xông hơi Page',
'fields' => array(
array(
'key' => 'field_6a12e4fa5ff4a',
'label' => 'Banner',
'name' => '',
'aria-label' => '',
'type' => 'tab',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'placement' => 'top',
'endpoint' => 0,
'selected' => 0,
),
array(
'key' => 'field_6a12e4fa5ff4f',
'label' => '',
'name' => 'banner_od',
'aria-label' => '',
'type' => 'clone',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'clone' => array(
0 => 'field_69fa9c1aa0533',
),
'display' => 'seamless',
'layout' => 'block',
'prefix_label' => 0,
'prefix_name' => 0,
),
array(
'key' => 'field_6a12e4fa5ff52',
'label' => 'Story',
'name' => '',
'aria-label' => '',
'type' => 'tab',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'placement' => 'top',
'endpoint' => 0,
'selected' => 0,
),
array(
'key' => 'field_6a12e4fa5ff54',
'label' => '',
'name' => 'restaurant_about',
'aria-label' => '',
'type' => 'group',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
array(
'key' => 'field_6a12e4fa6226f',
'label' => 'Subtile',
'name' => 'subtile',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_6a12e4fa62273',
'label' => 'Title',
'name' => 'label',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_6a12e4fa62276',
'label' => 'Description',
'name' => 'description',
'aria-label' => '',
'type' => 'textarea',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'rows' => '',
'placeholder' => '',
'new_lines' => '',
),
array(
'key' => 'field_6a12e4fa62278',
'label' => 'Content',
'name' => 'body_paragraphs',
'aria-label' => '',
'type' => 'repeater',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'layout' => 'table',
'pagination' => 0,
'min' => 0,
'max' => 0,
'collapsed' => '',
'button_label' => 'Add Row',
'rows_per_page' => 20,
'sub_fields' => array(
array(
'key' => 'field_6a12e4fa64149',
'label' => 'Text',
'name' => 'text',
'aria-label' => '',
'type' => 'textarea',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'rows' => '',
'placeholder' => '',
'new_lines' => '',
'parent_repeater' => 'field_6a12e4fa62278',
),
),
),
array(
'key' => 'field_6a12e4fa6227e',
'label' => 'Images',
'name' => 'images',
'aria-label' => '',
'type' => 'gallery',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'return_format' => 'array',
'library' => 'all',
'min' => '',
'max' => '',
'min_width' => '',
'min_height' => '',
'min_size' => '',
'max_width' => '',
'max_height' => '',
'max_size' => '',
'mime_types' => '',
'insert' => 'append',
'preview_size' => 'medium',
),
),
),
array(
'key' => 'field_6a12e4fa5ff57',
'label' => 'Services',
'name' => '',
'aria-label' => '',
'type' => 'tab',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'placement' => 'top',
'endpoint' => 0,
'selected' => 0,
),
array(
'key' => 'field_6a12e4fa5ff5a',
'label' => '',
'name' => 'service_od',
'aria-label' => '',
'type' => 'clone',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'clone' => array(
0 => 'field_69faa647d3f60',
),
'display' => 'seamless',
'layout' => 'block',
'prefix_label' => 0,
'prefix_name' => 0,
),
array(
'key' => 'field_6a12e4fa5ff5d',
'label' => 'Process',
'name' => '',
'aria-label' => '',
'type' => 'tab',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'placement' => 'top',
'endpoint' => 0,
'selected' => 0,
),
array(
'key' => 'field_xong_hoi_process',
'label' => '',
'name' => 'xong_hoi_process',
'aria-label' => '',
'type' => 'group',
'instructions' => 'Nội dung quy trình trải nghiệm nhiệt trị liệu. Để trống field sẽ dùng nội dung mặc định hiện có trên giao diện.',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
array(
'key' => 'field_xong_hoi_process_title',
'label' => 'Tiêu đề',
'name' => 'title',
'type' => 'text',
),
array(
'key' => 'field_xong_hoi_process_subtitle',
'label' => 'Mô tả',
'name' => 'subtitle',
'type' => 'textarea',
'rows' => 2,
'new_lines' => '',
),
array(
'key' => 'field_xong_hoi_process_step_one',
'label' => 'Bước 1',
'name' => 'step_one',
'type' => 'group',
'layout' => 'block',
'sub_fields' => array(
array(
'key' => 'field_xong_hoi_process_step_one_kicker',
'label' => 'Nhãn bước',
'name' => 'kicker',
'type' => 'text',
),
array(
'key' => 'field_xong_hoi_process_step_one_title',
'label' => 'Tiêu đề',
'name' => 'title',
'type' => 'text',
),
array(
'key' => 'field_xong_hoi_process_step_one_description',
'label' => 'Mô tả',
'name' => 'description',
'type' => 'textarea',
'rows' => 3,
'new_lines' => '',
),
array(
'key' => 'field_xong_hoi_process_step_one_image',
'label' => 'Hình ảnh',
'name' => 'image',
'type' => 'image',
'return_format' => 'url',
'preview_size' => 'medium',
'library' => 'all',
),
array(
'key' => 'field_xong_hoi_process_step_one_caption',
'label' => 'Chú thích hình',
'name' => 'caption',
'type' => 'text',
),
),
),
array(
'key' => 'field_xong_hoi_process_step_two',
'label' => 'Bước 2',
'name' => 'step_two',
'type' => 'group',
'layout' => 'block',
'sub_fields' => array(
array(
'key' => 'field_xong_hoi_process_step_two_kicker',
'label' => 'Nhãn bước',
'name' => 'kicker',
'type' => 'text',
),
array(
'key' => 'field_xong_hoi_process_step_two_title',
'label' => 'Tiêu đề',
'name' => 'title',
'type' => 'text',
),
array(
'key' => 'field_xong_hoi_process_journeys',
'label' => 'Hành trình',
'name' => 'journeys',
'type' => 'repeater',
'layout' => 'block',
'button_label' => 'Thêm hành trình',
'sub_fields' => array(
array(
'key' => 'field_xong_hoi_process_journey_label',
'label' => 'Tên hành trình',
'name' => 'label',
'type' => 'text',
),
array(
'key' => 'field_xong_hoi_process_journey_groups',
'label' => 'Nhóm hoạt động',
'name' => 'groups',
'type' => 'repeater',
'layout' => 'block',
'button_label' => 'Thêm nhóm',
'sub_fields' => array(
array(
'key' => 'field_xong_hoi_process_journey_group_heading',
'label' => 'Tiêu đề nhóm',
'name' => 'heading',
'type' => 'text',
),
array(
'key' => 'field_xong_hoi_process_journey_items',
'label' => 'Hoạt động',
'name' => 'items',
'type' => 'repeater',
'layout' => 'table',
'button_label' => 'Thêm hoạt động',
'sub_fields' => array(
array(
'key' => 'field_xong_hoi_process_journey_item_image',
'label' => 'Hình ảnh',
'name' => 'image',
'type' => 'image',
'return_format' => 'url',
'preview_size' => 'thumbnail',
'library' => 'all',
),
array(
'key' => 'field_xong_hoi_process_journey_item_text',
'label' => 'Nội dung',
'name' => 'text',
'type' => 'text',
),
),
),
),
),
),
),
array(
'key' => 'field_xong_hoi_process_step_two_choice',
'label' => 'Dòng kết',
'name' => 'choice',
'type' => 'text',
),
),
),
array(
'key' => 'field_xong_hoi_process_step_three',
'label' => 'Bước 3',
'name' => 'step_three',
'type' => 'group',
'layout' => 'block',
'sub_fields' => array(
array(
'key' => 'field_xong_hoi_process_step_three_kicker',
'label' => 'Nhãn bước',
'name' => 'kicker',
'type' => 'text',
),
array(
'key' => 'field_xong_hoi_process_step_three_title',
'label' => 'Tiêu đề',
'name' => 'title',
'type' => 'text',
),
array(
'key' => 'field_xong_hoi_process_tips',
'label' => 'Lưu ý',
'name' => 'tips',
'type' => 'repeater',
'layout' => 'block',
'button_label' => 'Thêm lưu ý',
'sub_fields' => array(
array(
'key' => 'field_xong_hoi_process_tip_icon',
'label' => 'Class biểu tượng',
'name' => 'icon',
'type' => 'text',
'instructions' => 'Dùng water, clock, quiet hoặc rest để áp dụng kiểu biểu tượng tương ứng.',
),
array(
'key' => 'field_xong_hoi_process_tip_image',
'label' => 'Hình biểu tượng',
'name' => 'image',
'type' => 'image',
'return_format' => 'url',
'preview_size' => 'thumbnail',
'library' => 'all',
),
array(
'key' => 'field_xong_hoi_process_tip_title',
'label' => 'Tiêu đề',
'name' => 'title',
'type' => 'text',
),
array(
'key' => 'field_xong_hoi_process_tip_text',
'label' => 'Nội dung',
'name' => 'text',
'type' => 'textarea',
'rows' => 2,
'new_lines' => '',
),
),
),
array(
'key' => 'field_xong_hoi_process_step_three_relax',
'label' => 'Dòng kết',
'name' => 'relax',
'type' => 'text',
),
),
),
array(
'key' => 'field_xong_hoi_process_note',
'label' => 'Ghi chú cuối section',
'name' => 'note',
'type' => 'textarea',
'rows' => 2,
'new_lines' => '',
),
),
),
array(
'key' => 'field_6a12e4fa5ff68',
'label' => '',
'name' => 'offer_od',
'aria-label' => '',
'type' => 'clone',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'clone' => array(
0 => 'field_69fab43e7325d',
),
'display' => 'seamless',
'layout' => 'block',
'prefix_label' => 0,
'prefix_name' => 0,
),
),
'location' => array(
array(
array(
'param' => 'page_template',
'operator' => '==',
'value' => 'xong-hoi-page.php',
),
),
),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
'show_in_rest' => 0,
) );
} );
